### ISSUE TITLE
Rename inc to include

### ISSUE THREAD

**Issue by egorpugin** [I3ck/FlaggedT#2]
Hi,

'include' dir is more common name in c++ project layout.
Could you please change inc to include?

**Comment by I3ck** [comment]
Now using the project name instead https://github.com/I3ck/FlaggedT/commit/00244a14ed5d7d48e85f499ec7dc0426b9688a20

**Comment by egorpugin** [comment]
Thanks! That's better than old name.

But what about one of these:
1. 'FlaggedT' - starting with captical
2. 'flaggedt' - all lowercase
3. 'include/flaggedt' - under include dir (also very common, like 'include/boost' ...)
4. 'include/FlaggedT' - same but with capitals.
